// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAls86rLYetJZJETzHFbmJDH3rG3M8ZKLc',
    appId: '1:506195907015:web:9f5fd76e612d8564af89e2',
    messagingSenderId: '506195907015',
    projectId: 'app-dron-a6653',
    authDomain: 'app-dron-a6653.firebaseapp.com',
    databaseURL: 'https://app-dron-a6653-default-rtdb.firebaseio.com',
    storageBucket: 'app-dron-a6653.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wM6ZStddH-3wB-Qj4Tvz70F96Ei5qVM',
    appId: '1:506195907015:android:c7b5b54ec37fa384af89e2',
    messagingSenderId: '506195907015',
    projectId: 'app-dron-a6653',
    databaseURL: 'https://app-dron-a6653-default-rtdb.firebaseio.com',
    storageBucket: 'app-dron-a6653.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFnG1ShOjDc2RD_zxTlWuqfyamLK9PrfU',
    appId: '1:506195907015:ios:243361c360d96d3faf89e2',
    messagingSenderId: '506195907015',
    projectId: 'app-dron-a6653',
    databaseURL: 'https://app-dron-a6653-default-rtdb.firebaseio.com',
    storageBucket: 'app-dron-a6653.firebasestorage.app',
    iosClientId: '506195907015-7ffjgmivv6fhurocdshmdn8tj582oqm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app12',
  );
}
